package com.example.chatapp.mapper;

import com.example.chatapp.model.FriendShip;
import com.example.chatapp.model.FiendShipExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FiendShipMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    long countByExample(FiendShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int deleteByExample(FiendShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int insert(FriendShip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int insertSelective(FriendShip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    List<FriendShip> selectByExample(FiendShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    FriendShip selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByExampleSelective(@Param("row") FriendShip row, @Param("example") FiendShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByExample(@Param("row") FriendShip row, @Param("example") FiendShipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByPrimaryKeySelective(FriendShip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendship
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByPrimaryKey(FriendShip row);
}