package com.example.chatapp.mapper;

import com.example.chatapp.model.FriendRequest;
import com.example.chatapp.model.FriendRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    long countByExample(FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int deleteByExample(FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int insert(FriendRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int insertSelective(FriendRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    List<FriendRequest> selectByExample(FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    FriendRequest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByExampleSelective(@Param("row") FriendRequest row, @Param("example") FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByExample(@Param("row") FriendRequest row, @Param("example") FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByPrimaryKeySelective(FriendRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friendrequest
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByPrimaryKey(FriendRequest row);
}