package com.example.chatapp.mapper;

import com.example.chatapp.model.Message;
import com.example.chatapp.model.MessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    long countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    
    int deleteOldMessages();
    
    
    int insert(Message row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int insertSelective(Message row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    List<Message> selectByExampleWithBLOBs(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    Message selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByExampleSelective(@Param("row") Message row, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByExampleWithBLOBs(@Param("row") Message row, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByExample(@Param("row") Message row, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByPrimaryKeySelective(Message row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByPrimaryKeyWithBLOBs(Message row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    int updateByPrimaryKey(Message row);
}