package com.example.chatapp.mapper;

import com.example.chatapp.model.User;
import com.example.chatapp.model.UserExample;
import com.example.chatapp.model.UserKey;
import com.example.chatapp.model.UserWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	long countByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	int deleteByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	int insert(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	int insertSelective(User row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	List<User> selectByExample(UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	int updateByExampleSelective(@Param("row") User row, @Param("example") UserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	int updateByExample(@Param("row") User row, @Param("example") UserExample example);
}