package com.example.chatapp.model;

public class Conversation_ParticipantKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation_participant.conversationId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String conversationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column conversation_participant.userId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation_participant.conversationId
     *
     * @return the value of conversation_participant.conversationId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getConversationid() {
        return conversationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation_participant.conversationId
     *
     * @param conversationid the value for conversation_participant.conversationId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setConversationid(String conversationid) {
        this.conversationid = conversationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column conversation_participant.userId
     *
     * @return the value of conversation_participant.userId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column conversation_participant.userId
     *
     * @param userid the value for conversation_participant.userId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }
}