package com.example.chatapp.model;

import java.util.Date;

public class FriendShip {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendship.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendship.user
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendship.friend
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String friend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendship.createdAt
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private Date createdat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendship.id
     *
     * @return the value of friendship.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendship.id
     *
     * @param id the value for friendship.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendship.user
     *
     * @return the value of friendship.user
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getUser() {
        return user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendship.user
     *
     * @param user the value for friendship.user
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setUser(String user) {
        this.user = user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendship.friend
     *
     * @return the value of friendship.friend
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getFriend() {
        return friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendship.friend
     *
     * @param friend the value for friendship.friend
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setFriend(String friend) {
        this.friend = friend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendship.createdAt
     *
     * @return the value of friendship.createdAt
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendship.createdAt
     *
     * @param createdat the value for friendship.createdAt
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }
}