package com.example.chatapp.model;

import java.util.Date;

public class FriendRequest {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendrequest.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendrequest.sender
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String sender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendrequest.receiver
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friendrequest.createdAt
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private Date createdat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendrequest.id
     *
     * @return the value of friendrequest.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendrequest.id
     *
     * @param id the value for friendrequest.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendrequest.sender
     *
     * @return the value of friendrequest.sender
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendrequest.sender
     *
     * @param sender the value for friendrequest.sender
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendrequest.receiver
     *
     * @return the value of friendrequest.receiver
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendrequest.receiver
     *
     * @param receiver the value for friendrequest.receiver
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friendrequest.createdAt
     *
     * @return the value of friendrequest.createdAt
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public Date getCreatedat() {
        return createdat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friendrequest.createdAt
     *
     * @param createdat the value for friendrequest.createdAt
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setCreatedat(Date createdat) {
        this.createdat = createdat;
    }
}