package com.example.chatapp.model;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.timeStamp
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private Date timestamp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.senderId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String senderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.conversationId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String conversationid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.content
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.timeStamp
     *
     * @return the value of message.timeStamp
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.timeStamp
     *
     * @param timestamp the value for message.timeStamp
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.senderId
     *
     * @return the value of message.senderId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getSenderid() {
        return senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.senderId
     *
     * @param senderid the value for message.senderId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setSenderid(String senderid) {
        this.senderid = senderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.conversationId
     *
     * @return the value of message.conversationId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getConversationid() {
        return conversationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.conversationId
     *
     * @param conversationid the value for message.conversationId
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setConversationid(String conversationid) {
        this.conversationid = conversationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.content
     *
     * @return the value of message.content
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.content
     *
     * @param content the value for message.content
     *
     * @mbg.generated Mon Mar 03 11:09:10 ICT 2025
     */
    public void setContent(String content) {
        this.content = content;
    }
}