package com.example.chatapp.model;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.userId
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	private String userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.fullName
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	private String fullname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.phone
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.dateOfBirth
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	private Date dateofbirth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.isActive
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	private Boolean isactive;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.userId
	 * @return  the value of user.userId
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.userId
	 * @param userid  the value for user.userId
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.fullName
	 * @return  the value of user.fullName
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public String getFullname() {
		return fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.fullName
	 * @param fullname  the value for user.fullName
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
	 * @return  the value of user.email
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
	 * @param email  the value for user.email
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.phone
	 * @return  the value of user.phone
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.phone
	 * @param phone  the value for user.phone
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.dateOfBirth
	 * @return  the value of user.dateOfBirth
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public Date getDateofbirth() {
		return dateofbirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.dateOfBirth
	 * @param dateofbirth  the value for user.dateOfBirth
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public void setDateofbirth(Date dateofbirth) {
		this.dateofbirth = dateofbirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.isActive
	 * @return  the value of user.isActive
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public Boolean getIsactive() {
		return isactive;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.isActive
	 * @param isactive  the value for user.isActive
	 * @mbg.generated  Mon Mar 03 11:09:10 ICT 2025
	 */
	public void setIsactive(Boolean isactive) {
		this.isactive = isactive;
	}
}